# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, windows]
        version: [3.1.424, 5.0.100, 6.0.402]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.version }}
    - name: Restore dependencies
      run: dotnet restore "./actionsdemoapp/actionsdemoapp/actionsdemoapp.csproj"
    - name: Build
      run: dotnet build "./actionsdemoapp/actionsdemoapp/actionsdemoapp.csproj" --no-restore
